### ISSUE TITLE
Error loading config open : The system cannot find the file specified

### ISSUE THREAD

**Issue by ra3ggi** [shemanaev/inpxer#1]
В версии  под Windows не видит конфиг файл, хотя он переименован  как надо и лежит рядом с исполняемым.

**Comment by shemanaev** [comment]
Можно вывод `dir` посмотреть?

**Comment by ra3ggi** [comment]
C:\Users\AlexK>dir c:\My_program\inpxer\
 Том в устройстве C не имеет метки.
 Серийный номер тома: 3CDF-CA73

 Содержимое папки c:\My_program\inpxer

09.10.2022  21:20    <DIR>          .
09.10.2022  21:20    <DIR>          ..
09.10.2022  20:33    <DIR>          data
07.09.2022  11:32        18 352 640 inpxer.exe
09.10.2022  20:41               704 inpxer.toml
07.09.2022  11:34             1 071 LICENSE
07.09.2022  11:34             1 151 README.md
               4 файлов     18 355 566 байт
               3 папок  621 394 067 456 байт свободно

**Comment by shemanaev** [comment]
А как запускается сервер? Конфиг ищется относительно рабочей директории, а не исполняемого файла.

**Comment by ra3ggi** [comment]
c:\My_program\inpxer\inpxer.exe i e:\fb2.Flibusta.Net\flibusta_fb2_local.inpx
2022/10/09 21:23:35 error loading config open : The system cannot find the file specified.

**Comment by ra3ggi** [comment]
"Конфиг ищется относительно рабочей директории, а не исполняемого файла."

Все , я понял в чем дело, но это очень не явно. 
Конфиг положил в C:\Users\AlexK - тогда запустилось 
Спасибо - сам бы не разобрался.

**Comment by shemanaev** [comment]
> Все , я понял в чем дело, но это очень не явно.

Согласен, поправлю это.

**Comment by ra3ggi** [comment]
А команда на ОСТАНОВКУ сервера есть?

**Comment by shemanaev** [comment]
Т.к. он запускается не в фоне, то стандартно для консольных приложений Ctrl+C. Если хочется как службу его установить, то можно что-нибудь вроде [NSSM](https://nssm.cc/usage) использовать.

**Comment by ra3ggi** [comment]
Ок , понял , спасибо за прекрасную разработку - от поиска просто в восторге !

**Comment by shemanaev** [comment]
Опубликовал [новую версию](https://github.com/shemanaev/inpxer/releases/tag/v0.2.1), кинфиги ищет как положено 😄 .

**Comment by ra3ggi** [comment]
Очень бы хотелось иметь возможность захода по логину и паролю как на web так и на opds/
Удачи!

**Comment by shemanaev** [comment]
Вообще нет в планах, потому что если подходить к делу серьёзно (и пускать в открытый интернет), то лучше использовать реверс-прокси вроде nginx или traefik. Для приватных сервисов я предпочитаю VPN вроде Tailscale и ZeroTier. А какой у вас сценарий использования для аутентификации?

**Comment by ra3ggi** [comment]
Ну , вэб-форму в инет выкладывать в планах нет, а OPDS - проброшу портами. И как-то совсем без авторизации не красиво. Хотя может быть Вы и правы, и особой необходимости в этом нет, выбрать нестандартные порты и всё.

**Comment by ra3ggi** [comment]
Сегодня тестил OPDS - файлы скачиваются с расширением UNK. Хотя если переименовать в fb2 - читаются как положено.

**Comment by ra3ggi** [comment]
Работает, конечно, в разы быстрее чем TinyOPDS, но очень не хватает функции, когда нажимаешь на книгу и появляется аннотация и обложка.

**Comment by shemanaev** [comment]
> Сегодня тестил OPDS - файлы скачиваются с расширением UNK. Хотя если переименовать в fb2 - читаются как положено.

Какая читалка?

> нажимаешь на книгу и появляется аннотация и обложка.

Вряд ли будет добавлено. Этой информации в inpx нет, а если сканировать все файлы книг, то есть прекрасный Calibre, например.

**Comment by shemanaev** [comment]
> Сегодня тестил OPDS - файлы скачиваются с расширением UNK.

В браузере тоже так?

**Comment by ra3ggi** [comment]
В броузере - нормально скачивается в fb2, а через OPDS - расширение у файла не верное, хотя сам файл нормальный.
Чbталка - Alreader

**Comment by shemanaev** [comment]
Кажется, проблема не в читалке. Можно inpx файл посмотреть?

**Comment by ra3ggi** [comment]
Качал  inpx здесь :
https://rutracker.org/forum/viewtopic.php?t=5462398

**Comment by shemanaev** [comment]
Честно говоря, так и не удалось воспроизвести проблему. Можете проверить на тестовой версии? [inpxer.zip](https://github.com/shemanaev/inpxer/files/9745045/inpxer.zip)

**Comment by ra3ggi** [comment]
С новым файлом качает правильно. Вернул старый и вот скрин - https://i.imgur.com/wTyCDiJ.png
Так что проблему вы исправили в тестовой версии :)

**Comment by ra3ggi** [comment]
Еще момент - я так понимаю , что при первоначальном индексировании папка , указанная в конфиге
index_path = "......" очищается? Т.е. там удаляются все файлы.
Изначально юзер не знает об этом , он думает , что будет просто создан файл индексирования и может  указать папку с книгами (типа пусть индекс там лежит), которая благополучно очистится.

**Comment by shemanaev** [comment]
> Т.е. там удаляются все файлы.

Да, в ридми это описано.

**Comment by ra3ggi** [comment]
Не , в ридми не описано , что в папке удалятся ВСЕ файлы. Поэтому возможна ситуация , которую я описал - юзер потеряет все книги , указав папку с ними в качестве целевой для файла индекса.

**Comment by shemanaev** [comment]
> Otherwise, old index data will be deleted (the whole folder specified in `index_path`) and reindex from scratch.

Такого уточнения будет достаточно?

**Comment by ra3ggi** [comment]
Ну может и достаточно , но я бы строго написал бы , что мол , создайте ОТДЕЛЬНУЮ папку для файлов индекса. Кто-то может недопонять, а папка  с книгами весит много и некоторые качают её неделю - потерять все эти файлы - будет грустно...
