### ISSUE TITLE
encoding problem in downloaded file names

### ISSUE THREAD

**Issue by Daniil-Gusev** [shemanaev/inpxer#4]
Book titles in Russian. When downloading, the server returns files with names similar to this: "%D0%9E%D0%B1%D0%BB%D0%BE%D0%BC%D0%BE%D0%B2-772796.epub".

**Comment by shemanaev** [comment]
How exactly do you download a file? Browser (version, OS)? Reader?

**Comment by Daniil-Gusev** [comment]
> How exactly do you download a file? Browser (version, OS)? Reader?

I download the file via the web interface on the iPhone (Safari 17.6). The problem concerns only the file name, the content is fine. If you download the book using opds, the file has the correct name in Russian.

**Comment by shemanaev** [comment]
Fixed in [v0.2.6](https://github.com/shemanaev/inpxer/releases/tag/v0.2.6)
